abstract: JSON is YAML
author: Audrey Tang <autrijus@autrijus.org>
distribution_type: module
generated_by: Module::Install version 0.52
license: unknown
name: JSON-Syck
no_index:
  directory:
    - inc
    - t
version: 0.01
